gallery/routes/web.php
<?php

use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\PhotosController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController as AdminUsersController;
use App\Http\Controllers\Admin\CommentsController as AdminCommentsController;
use App\Http\Controllers\Admin\PhotosController as AdminPhotosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('language')->group(function () {
    Route::get('/', [PhotosController::class, 'index'])->name('home')->middleware(['language']);
    Route::resource('photos', PhotosController::class)->middleware(['auth', 'language']);
    Auth::routes();
    Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
        Route::resources(
            [
                'comments' => AdminCommentsController::class,
                'users' => AdminUsersController::class,
                'photos' => AdminPhotosController::class
            ]
        );
    });
    Route::resource('photos.comments', CommentsController::class)->middleware(['auth', 'language']);
    Route::resource('comments', CommentsController::class)->middleware(['auth', 'language'])->except('store');
    Route::get('/photos/{photo}/comment', [CommentsController::class, 'store'])->name('comments.store');
    Route::resource('users', UserController::class)->middleware(['auth', 'language']);
});

Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

gallery/app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'body', 'rating', 'photo_id'];

    /**
     * @return BelongsTo
     */
    public function Photo()
    {
        return $this->belongsTo(Photo::class)->latest();
    }

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class)->latest();
    }
}

gallery/app/Http/Controllers/Admin/CommentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Photo;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $comments = Comment::all();
        return view('admin.comments.index', compact('comments'));
    }

    /**
     * @param Request $request
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function store(Request $request, Photo $photo)
    {
        $request->validate([
            'body' => 'required|min:5',
            'rating' => 'required|in:1,2,3,4,5',
            'photo_id' => 'required'
        ]);
        $comment = new Comment();
        $comment->user_id = $request->user()->id;
        $comment->body = $request->input('body');
        $comment->rating = $request->input('rating');
        $comment->photo_id = $photo->id;
        $comment->save();
        return back();
    }

    /**
     * @param Comment $comment
     * @return Application|Factory|View
     */
    public function edit(Comment $comment)
    {
        $photos = Photo::all();
        return view('admin.comments.edit', compact('comment', 'photos'));
    }

    /**
     * @param Comment $comment
     * @return Application|Factory|View
     */
    public function create(Comment $comment)
    {
        $photos = Photo::all();
        return view('admin.comments.create', compact('comment', 'photos'));
    }

    /**
     * @param Request $request
     * @param Comment $comment
     * @return RedirectResponse
     */
    public function update(Request $request, Comment $comment)
    {
        $request->validate([
            'body' => 'required|min:5',
            'rating' => 'required|in:1,2,3,4,5'
        ]);
        $comment->update($request->all());
        return redirect()->route('admin.comments.index', $comment->photo_id);
    }

    /**
     * @param Comment $comment
     * @return RedirectResponse
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();
        return redirect()->route('admin.comments.index', $comment->photo_id);
    }
}

gallery/app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Photo;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * @param Request $request
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function store(Request $request, Photo $photo)
    {
        $request->validate([
            'body' => 'required|min:5',
            'rating' => 'required|in:1,2,3,4,5'
        ]);
        $comment = new Comment();
        $comment->user_id = $request->user()->id;
        $comment->body = $request->input('body');
        $comment->rating = $request->input('rating');
        $comment->photo_id = $photo->id;
        $comment->save();
        return back();
    }

    /**
     * @param Comment $comment
     * @return View|Factory|Application
     */
    public function edit(Comment $comment)
    {
        $this->authorize('update', $comment);
        return view('client.comments.edit', compact('comment'));
    }

    /**
     * @param Request $request
     * @param Comment $comment
     * @return RedirectResponse
     */
    public function update(Request $request, Comment $comment)
    {
        $this->authorize('update', $comment);
        $request->validate([
            'body' => 'required|min:5',
            'rating' => 'required|in:1,2,3,4,5'
        ]);
        $comment->update($request->all());
        return redirect()->route('photos.show', $comment->photo_id);
    }

    /**
     * @param Comment $comment
     * @return RedirectResponse
     */
    public function destroy(Comment $comment)
    {
        $this->authorize('delete', $comment);
        $comment->delete();
        return redirect()->route('photos.show', $comment->photo_id);
    }
}

gallery/resources/views/client/comments/comment.blade.php
<div class="">
    <div class="media g-mb-30 media-comment">
        <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
            <div class="g-mb-15">
                @can('update', $comment)
                    <a href="{{route('comments.edit', ['comment' => $comment])}}"
                       class="btn btn-primary">@lang('messages.edit')</a>
                @endcan
                @can('delete', $comment)
                    <form method="post" action="{{route('comments.destroy', ['comment' => $comment])}}">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-danger">@lang('messages.delete')</button>
                    </form>
                @endcan
                <h4 class="h5 g-color-gray-dark-v1 mb-0">{{$comment->rating}}</h4>
                <h5 class="h5 g-color-gray-dark-v1 mb-0">{{$comment->user->name}}</h5>
                <span class="g-color-gray-dark-v4 g-font-size-12">{{$comment->created_at->diffForHumans()}}</span>
            </div>
            <p>
                {{$comment->body}}
            </p>
        </div>
    </div>
</div>

gallery/resources/views/client/comments/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1>@lang('messages.editComment')</h1>
    <form method="post" action="{{ route('comments.update', ['comment' => $comment]) }}">
        @method('put')
        @csrf
        <div class="form-group">
        <label for="rating"><strong>@lang('messages.chooseRating')</strong></label>
        <select name="rating" id="rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
        </div>
        <div class="form-group">
            <label for="description">@lang('messages.body')</label>
            <textarea class="form-control  @error('body') is-invalid @enderror" id="body"
                      name="body">{{$comment->body}}</textarea>
            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">@lang('messages.update')</button>
    </form>
@endsection