gallery/routes/web.php
<?php

use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\PhotosController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController as AdminUsersController;
use App\Http\Controllers\Admin\CommentsController as AdminCommentsController;
use App\Http\Controllers\Admin\PhotosController as AdminPhotosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('language')->group(function () {
    Route::get('/', [PhotosController::class, 'index'])->name('home')->middleware(['language']);
    Route::resource('photos', PhotosController::class)->middleware(['auth', 'language']);
    Auth::routes();
    Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
        Route::resources(
            [
                'comments' => AdminCommentsController::class,
                'users' => AdminUsersController::class,
                'photos' => AdminPhotosController::class
            ]
        );
    });
    Route::resource('photos.comments', CommentsController::class)->middleware(['auth', 'language']);
    Route::resource('comments', CommentsController::class)->middleware(['auth', 'language'])->except('store');
    Route::get('/photos/{photo}/comment', [CommentsController::class, 'store'])->name('comments.store');
    Route::resource('users', UserController::class)->middleware(['auth', 'language']);
});

Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

gallery/app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @method static Paginate(int $int)
 */
class Photo extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'picture', 'user_id'];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class)->latest();
    }


    /**
     * @return HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class)->latest();
    }
}

gallery/app/Http/Controllers/Admin/PhotosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Form\PhotoForm;
use App\Http\Requests\GenreRequest;
use App\Http\Requests\PhotoRequest;
use App\Models\Genre;
use App\Models\Photo;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class PhotosController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $photos = Photo::all();
        return view('admin.photos.index', compact('photos'));
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.photos.create');
    }


    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function show(Photo $photo)
    {
        return view('admin.photos.show', compact('photo'));
    }

    /**
     * @param PhotoRequest $request
     * @return RedirectResponse
     */
    public function store(PhotoRequest $request)
    {
        $photo = PhotoForm::execute($request);
        return redirect()->route('admin.photos.index')->with('status', "{$photo->title} successfully created!");
    }

    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function edit(Photo $photo)
    {
        return view('admin.photos.edit', compact('photo'));
    }

    /**
     * @param PhotoRequest $request
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function update(PhotoRequest $request, Photo $photo)
    {
        $data = $request->all();
        if ($request->hasFile('picture')) {
            $file = $request->file('picture');
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $photo->update($data);
        return redirect()->action([self::class, 'index'], ['photo' => $photo])->with('status', "Photo {$photo->title} successfully updated!");
    }

    /**
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function destroy(Photo $photo)
    {
        $photo->delete();
        return redirect()->route('admin.photos.index')->with('status', "Photo successfully deleted!");
    }
}

gallery/app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Form\PhotoForm;
use App\Http\Requests\PhotoRequest;
use App\Models\Photo;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class PhotosController extends Controller
{

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $photos = Photo::Paginate(6);
        return view('client.photos.index', compact('photos'));
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('client.photos.create');
    }


    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function show(Photo $photo)
    {
        return view('client.photos.show', compact('photo'));
    }

    /**
     * @param PhotoRequest $request
     * @return RedirectResponse
     */
    public function store(PhotoRequest $request)
    {
        $photo = PhotoForm::execute($request);
        return redirect()->route('photos.index')->with('status', "{$photo->title} successfully created!");
    }

    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function edit(Photo $photo)
    {
        return view('client.photos.edit', compact('photo'));
    }

    /**
     * @param PhotoRequest $request
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function update(PhotoRequest $request, Photo $photo)
    {
        $data = $request->all();
        if ($request->hasFile('picture')) {
            $file = $request->file('picture');
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $photo->update($data);
        return redirect()->action([self::class, 'index'], ['photo' => $photo])->with('status', "Photo {$photo->title} successfully updated!");
    }

    /**
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function destroy(Photo $photo)
    {
        $photo->delete();
        return redirect()->route('photos.index')->with('status', "Photo successfully deleted!");
    }
}

gallery/resources/views/admin/photos/create.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Create new book</h1>
    <form enctype="multipart/form-data" method="post" action="{{ route('admin.photos.store') }}">
        @csrf
        <div class="form-group">
            <label for="title">Название</label>
            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title"
                   value="name"/>
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('picture') is-invalid @enderror" id="customFile"
                       name="picture" value="picture">
                @error('picture')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

gallery/resources/views/admin/photos/edit.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Редактировать жанр</h1>
    <form enctype="multipart/form-data" method="post" action="{{ route('admin.photos.update', ['photo' => $photo]) }}">
        @csrf
        <div class="form-group">
            <label for="title">Название</label>
            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title"
                   value="{{$photo->title}}"/>
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('picture') is-invalid @enderror" id="customFile"
                       name="picture" value="picture">
                @error('picture')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

gallery/resources/views/admin/photos/index.blade.php
@extends('layouts.admin')


@section('content')

    <div style="padding-bottom: 30px;">
        <h1>Все фото</h1>
        <a href="{{route('admin.photos.create')}}" type="button" class="btn btn-outline-primary">
           Добавить фото
        </a>
    </div>

    <table class="table" style="padding-top: 30px">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach($photos as $photo)
            <tr>
                <td>
                    {{$photo->title}}
                </td>
                <td>
                    <a class="btn btn-outline-primary" href="{{route('admin.photos.edit', ['photo' => $photo])}}">
                        Редактировать
                    </a>
                    <form method="post" action="{{route('admin.photos.destroy', ['photo' => $photo])}}">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-outline-danger">Удалить</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection