gallery/routes/web.php
<?php

use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\PhotosController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController as AdminUsersController;
use App\Http\Controllers\Admin\CommentsController as AdminCommentsController;
use App\Http\Controllers\Admin\PhotosController as AdminPhotosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('language')->group(function () {
    Route::get('/', [PhotosController::class, 'index'])->name('home')->middleware(['language']);
    Route::resource('photos', PhotosController::class)->middleware(['auth', 'language']);
    Auth::routes();
    Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
        Route::resources(
            [
                'comments' => AdminCommentsController::class,
                'users' => AdminUsersController::class,
                'photos' => AdminPhotosController::class
            ]
        );
    });
    Route::resource('photos.comments', CommentsController::class)->middleware(['auth', 'language']);
    Route::resource('comments', CommentsController::class)->middleware(['auth', 'language'])->except('store');
    Route::get('/photos/{photo}/comment', [CommentsController::class, 'store'])->name('comments.store');
    Route::resource('users', UserController::class)->middleware(['auth', 'language']);
});

Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])
    ->name('language.switcher')
    ->where('locale', 'en|ru');

gallery/app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @method static Paginate(int $int)
 */
class Photo extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'picture', 'user_id'];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class)->latest();
    }


    /**
     * @return HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class)->latest();
    }
}

gallery/app/Http/Controllers/Admin/PhotosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Form\PhotoForm;
use App\Http\Requests\GenreRequest;
use App\Http\Requests\PhotoRequest;
use App\Models\Genre;
use App\Models\Photo;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class PhotosController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $photos = Photo::all();
        return view('admin.photos.index', compact('photos'));
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.photos.create');
    }


    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function show(Photo $photo)
    {
        return view('admin.photos.show', compact('photo'));
    }

    /**
     * @param PhotoRequest $request
     * @return RedirectResponse
     */
    public function store(PhotoRequest $request)
    {
        $photo = PhotoForm::execute($request);
        return redirect()->route('admin.photos.index')->with('status', "{$photo->title} successfully created!");
    }

    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function edit(Photo $photo)
    {
        return view('admin.photos.edit', compact('photo'));
    }

    /**
     * @param PhotoRequest $request
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function update(PhotoRequest $request, Photo $photo)
    {
        $data = $request->all();
        if ($request->hasFile('picture')) {
            $file = $request->file('picture');
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $photo->update($data);
        return redirect()->action([self::class, 'index'], ['photo' => $photo])->with('status', "Photo {$photo->title} successfully updated!");
    }

    /**
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function destroy(Photo $photo)
    {
        $photo->delete();
        return redirect()->route('admin.photos.index')->with('status', "Photo successfully deleted!");
    }
}

gallery/app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Form\PhotoForm;
use App\Http\Requests\PhotoRequest;
use App\Models\Photo;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class PhotosController extends Controller
{

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $photos = Photo::Paginate(6);
        return view('client.photos.index', compact('photos'));
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('client.photos.create');
    }


    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function show(Photo $photo)
    {
        return view('client.photos.show', compact('photo'));
    }

    /**
     * @param PhotoRequest $request
     * @return RedirectResponse
     */
    public function store(PhotoRequest $request)
    {
        $photo = PhotoForm::execute($request);
        return redirect()->route('photos.index')->with('status', "{$photo->title} successfully created!");
    }

    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function edit(Photo $photo)
    {
        return view('client.photos.edit', compact('photo'));
    }

    /**
     * @param PhotoRequest $request
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function update(PhotoRequest $request, Photo $photo)
    {
        $data = $request->all();
        if ($request->hasFile('picture')) {
            $file = $request->file('picture');
            $path = $file->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $photo->update($data);
        return redirect()->action([self::class, 'index'], ['photo' => $photo])->with('status', "Photo {$photo->title} successfully updated!");
    }

    /**
     * @param Photo $photo
     * @return RedirectResponse
     */
    public function destroy(Photo $photo)
    {
        $photo->delete();
        return redirect()->route('photos.index')->with('status', "Photo successfully deleted!");
    }
}

gallery/resources/views/client/photos/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>@lang('messages.createPhoto')</h1>
    <form enctype="multipart/form-data" method="post" action="{{ route('photos.store') }}">
        @csrf
        <div class="form-group">
            <label for="title">@lang('messages.title')</label>
            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title"
                   value="name">
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('picture') is-invalid @enderror" id="customFile"
                       name="picture" value="picture">
                @error('picture')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <label class="custom-file-label" for="customFile">@lang('messages.chooseFile')</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">@lang('messages.submit')</button>
    </form>
@endsection

gallery/resources/views/client/photos/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @foreach($photos as $photo)
                <div class="card m-3" style="width: 18rem;">
                    <img src="{{asset('/storage/' . $photo->picture)}}" class="card-img-top"
                         style="height: 290px; width: auto" alt="{{asset('/storage/' . $photo->picture)}}"
                         width="50px" height="50px">
                    <div class="card-body">
                        <h5 class="card-title"><strong>@lang('messages.title')</strong> {{$photo->title}}</h5>
                        <h5 class="card-title"><strong>@lang('messages.author')</strong> {{$photo->user->name}}</h5>
                        <a href="{{route('photos.show', ['photo' => $photo])}}" class="btn btn-primary">@lang('messages.more')</a>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="row">
        <div class="col-md-auto">
            {{$photos->links('pagination::bootstrap-4')}}
        </div>
    </div>
@endsection

gallery/resources/views/client/photos/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="border-bottom pb-3 mb-3">
            <h3 class="pt-5 border-bottom pb-1 mb-3 ">@lang('messages.title') {{$photo->title}}</h3>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 .img-fluid. w-100%  h-auto ">
                <div class="col mb-4">
                    <h4>@lang('messages.author'):
                        <p>{{$photo->user->name}}</p>
                    </h4>
                    <br>
                </div>
                <div class="col mb-1 ">
                    <img src="{{asset('/storage/' . $photo->picture)}}"
                         class="rounded mx-auto d-block img-fluid rounded float-right"
                         alt="{{asset('/storage/' . $photo->picture)}}" width="200px" height="200px">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3>@lang('messages.comments')</h3>
            </div>
        </div>
        <h1>@lang('messages.createComment')</h1>
        <form method="get" action="{{ route('comments.store', ['photo' => $photo]) }}">
            @csrf
                <label for="rating"><strong>@lang('messages.chooseRating'):</strong></label>
                <select name="rating" id="rating">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            <div class="form-group">
                <label for="description">@lang('messages.body')</label>
                <textarea class="form-control @error('body') is-invalid @enderror" id="body"
                          name="body"></textarea>
                @error('body')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">@lang('messages.submit')</button>
            </form>
        <div class="row">
            <div class="col-8 scrollit">
                @foreach($photo->comments as $comment)
                    @include('client.comments.comment', ['comment' => $comment])
                @endforeach
            </div>
        </div>
@endsection